const postsData = [
	{
		id:1,
		image:"./images/section/post1.jpg",
		user:"Admin",
		comments:10,
		title:"Thanksgiving greeting card PSD",
		category:"Insipration",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:2,
		image:"./images/section/post1.jpg",
		user:"Admin",
		comments:10,
		title:"Thanksgiving greeting card PSD",
		category:"Insipration",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:3,
		image:"./images/section/post2.jpg",
		user:"Admin",
		comments:10,
		title:"Vintage business card PSD (front & back)",
		category:"Technology",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:4,
		image:"./images/section/post2.jpg",
		user:"Admin",
		comments:10,
		title:"Vintage business card PSD (front & back)",
		category:"Technology",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:5,
		image:"./images/section/post3.jpg",
		user:"Admin",
		comments:10,
		title:"Request a quote form PSD in 3 colors",
		category:"Freebies",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:6,
		image:"./images/section/post3.jpg",
		user:"Admin",
		comments:10,
		title:"Request a quote form PSD in 3 colors",
		category:"Freebies",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:7,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Wordpress",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:8,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Wordpress",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:9,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Fonts",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:10,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Fonts",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:11,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Tutorials",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:12,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Tutorials",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:13,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Wallpapers",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	},
	{
		id:14,
		image:"./images/section/post4.jpg",
		user:"Admin",
		comments:10,
		title:"PSD book template & icons",
		category:"Wallpapers",
		text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fermentum malesuada orci a commodo. Aenean dapibus urna quis nulla consequat sagittis. Quisque ut ultrices massa. Mauris felis felis, rutrum sit amet vehicula ut, tempus quis lectus. .",
	}
]

export const getPostsMap = (array) => {
	return array.reduce((obj,post) => ({
			...obj,
			[post.id]:post,
		}),{})
}

export default postsData